# Generated by Django 4.2.3 on 2024-11-29 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='can_be_sent',
            field=models.BooleanField(default=True),
        ),
    ]
